'use client'

import { useEffect,useState } from 'react'
import { ArrowLeft,HardHat,ListChecks,PackageCheck,Pencil,Play,Plus,Sparkles,Trash2 } from 'lucide-react'
type Supply={item:string;quantity:string;estimatedUnitCost:number;estimatedLineCost:number}
type BuildPlan={id:number;title:string;overview:string;steps:string[];supplies:Supply[];materialCost:number;laborTasks:string[];estimatedLaborHours:number;laborCost:number;estimatedTotalCost:number;assumptions:string[];safetyAndCodeNotes:string[];project:string;customer:string;createdAt:string}
type WorkspaceData={docs?:any[];projects?:any[];[key:string]:any}
const money=(n:number)=>'$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})

export default function BuildPlansPage(){
 const[customer,setCustomer]=useState(''),[project,setProject]=useState(''),[description,setDescription]=useState(''),[measurements,setMeasurements]=useState(''),[laborRate,setLaborRate]=useState('')
 const[plan,setPlan]=useState<BuildPlan|null>(null),[savedPlans,setSavedPlans]=useState<BuildPlan[]>([]),[workspace,setWorkspace]=useState<WorkspaceData>({})
 const[working,setWorking]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(''),[editing,setEditing]=useState(false),[estimateReviewed,setEstimateReviewed]=useState(false)
 useEffect(()=>{;(async()=>{try{const r=await fetch('/api/workspace',{cache:'no-store'});if(r.status===401){location.href='/login';return}if(!r.ok){setError('Workspace sync is temporarily unavailable. You can still generate a build plan.');return}const w=await r.json(),d=w.data||{};setWorkspace(d);const docs=Array.isArray(d.docs)?d.docs:[];setSavedPlans(docs.filter((x:any)=>x.type==='Build Plan'&&x.buildPlan).map((x:any)=>x.buildPlan))}catch{setError('Workspace sync is temporarily unavailable. You can still generate a build plan.')}})()},[])
 function normalize(j:any):BuildPlan{return{id:Date.now(),title:String(j.title||project),overview:String(j.overview||''),steps:Array.isArray(j.steps)?j.steps:[],supplies:Array.isArray(j.supplies)?j.supplies.map((s:any)=>({item:String(s.item||''),quantity:String(s.quantity||''),estimatedUnitCost:Number(s.estimatedUnitCost||0),estimatedLineCost:Number(s.estimatedLineCost||0)})):[],materialCost:Number(j.materialCost||0),laborTasks:Array.isArray(j.laborTasks)?j.laborTasks:[],estimatedLaborHours:Number(j.estimatedLaborHours||0),laborCost:Number(j.laborCost||0),estimatedTotalCost:Number(j.estimatedTotalCost||0),assumptions:Array.isArray(j.assumptions)?j.assumptions:[],safetyAndCodeNotes:Array.isArray(j.safetyAndCodeNotes)?j.safetyAndCodeNotes:[],project:project.trim(),customer:customer.trim(),createdAt:new Date().toISOString()}}
 async function generate(){if(!project.trim()||!description.trim())return;setWorking(true);setError('');setSaved('');setEditing(false);setEstimateReviewed(false);try{const input=[`Customer: ${customer||'Not provided'}`,`Project: ${project}`,`Job description: ${description}`,`Measurements / field notes: ${measurements||'Not provided'}`,`Labor rate: ${laborRate?'$'+laborRate+'/hour':'Use a reasonable planning allowance and clearly state it as an assumption.'}`,'Include a detailed supply list with quantities and estimated costs, material subtotal, labor estimate, total estimated cost, and clear step-by-step instructions explaining how to build the project.'].join('\n');const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'build_plan',input})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body?.error||'Build plan generation failed');let cleaned=String(body.text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/```\s*$/,'').trim();const first=cleaned.indexOf('{'),last=cleaned.lastIndexOf('}');if(first>=0&&last>first)cleaned=cleaned.slice(first,last+1);setPlan(normalize(JSON.parse(cleaned)))}catch(e:any){setError(`Build plan could not be displayed: ${e?.message||'Please try again.'}`)}finally{setWorking(false)}}
 function recalc(next:BuildPlan){const materialCost=next.supplies.reduce((sum,s)=>sum+Number(s.estimatedLineCost||0),0);return{...next,materialCost,estimatedTotalCost:materialCost+Number(next.laborCost||0)}}
 function markChanged(next:BuildPlan){setEstimateReviewed(false);setPlan(recalc(next))}
 function changeSupply(index:number,key:keyof Supply,value:string){if(!plan)return;const supplies=plan.supplies.map((s,i)=>{if(i!==index)return s;const next:any={...s};if(key==='item'||key==='quantity')next[key]=value;else next[key]=Number(value||0);if(key==='estimatedUnitCost'){const qty=Number(String(next.quantity).match(/[0-9]+(?:\.[0-9]+)?/)?.[0]||1);next.estimatedLineCost=qty*Number(next.estimatedUnitCost||0)}return next});markChanged({...plan,supplies})}
 function addSupply(){if(plan)markChanged({...plan,supplies:[...plan.supplies,{item:'',quantity:'1',estimatedUnitCost:0,estimatedLineCost:0}]})}
 function removeSupply(index:number){if(plan)markChanged({...plan,supplies:plan.supplies.filter((_,i)=>i!==index)})}
 function changeLabor(key:'estimatedLaborHours'|'laborCost',value:string){if(plan)markChanged({...plan,[key]:Number(value||0)})}
 async function savePlan(){if(!plan)return;const docs=Array.isArray(workspace.docs)?workspace.docs:[],next={...workspace,docs:[{id:plan.id,type:'Build Plan',customer:plan.customer,project:plan.project,status:'Draft',buildPlan:plan,content:JSON.stringify(plan)},...docs]};const r=await fetch('/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});if(!r.ok){setError('Build plan was generated, but could not be saved.');return}setWorkspace(next);setSavedPlans([plan,...savedPlans]);setSaved('Saved to this company workspace')}
 async function startJob(){if(!plan||!estimateReviewed)return;setWorking(true);setError('');try{const docs=Array.isArray(workspace.docs)?workspace.docs:[],projects=Array.isArray(workspace.projects)?workspace.projects:[];const jobId=Date.now();const scope=plan.steps.map((x,i)=>`${i+1}. ${x}`).join('\n');const supplyText=plan.supplies.map(s=>`• ${s.item} — ${s.quantity} — ${money(s.estimatedLineCost)}`).join('\n');const contract=`CONSTRUCTION AGREEMENT\n\nCustomer: ${plan.customer||'Customer'}\nProject: ${plan.project}\nApproved estimate: ${money(plan.estimatedTotalCost)}\n\nSCOPE OF WORK\n${scope}\n\nAPPROVED MATERIAL / SUPPLY ESTIMATE\n${supplyText}\n\nEstimated materials: ${money(plan.materialCost)}\nEstimated labor: ${money(plan.laborCost)} (${plan.estimatedLaborHours} hrs)\nEstimated total: ${money(plan.estimatedTotalCost)}\n\nThe parties acknowledge that this agreement is based on the approved BuildFlow project plan and estimate. Field conditions, permits, code requirements, material selections, payment schedule, change orders, warranties, and final schedule must be reviewed and agreed by the parties. Any change to the scope or price should be documented in writing before the changed work begins.\n\nBoth parties should review the complete agreement before signing.`;const next={...workspace,projects:[{id:jobId,customer:plan.customer||'Customer',name:plan.project,status:'Ready to Start',date:'Not scheduled',amount:plan.estimatedTotalCost},...projects],docs:[{id:jobId+1,type:'Contracts',customer:plan.customer||'Customer',project:plan.project,status:'Awaiting Signatures',content:contract,sourceBuildPlanId:plan.id,approvedEstimate:plan,estimateReviewed:true},...docs]};const r=await fetch('/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});if(!r.ok)throw new Error('Could not create the job');location.href=`/jobs?project=${jobId}&onboarding=1`}catch(e:any){setError(e?.message||'Could not start job')}finally{setWorking(false)}}
 async function removePlan(id:number){const docs=Array.isArray(workspace.docs)?workspace.docs:[],next={...workspace,docs:docs.filter((x:any)=>!(x.type==='Build Plan'&&x.buildPlan?.id===id))};const r=await fetch('/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});if(r.ok){setWorkspace(next);setSavedPlans(savedPlans.filter(x=>x.id!==id))}}
 return <main style={{maxWidth:1100,margin:'0 auto',padding:'28px 20px 60px',fontFamily:'system-ui',color:'#172033'}}>
  <a href="/" style={{display:'inline-flex',alignItems:'center',gap:7,color:'inherit',textDecoration:'none',fontWeight:700,marginBottom:22}}><ArrowLeft size={18}/> Back to BuildFlow HQ</a>
  <section style={{padding:26,borderRadius:20,background:'#172033',color:'white',marginBottom:22}}><div style={{display:'flex',alignItems:'center',gap:12}}><HardHat/><div><small>AI-POWERED PROJECT PLANNING</small><h1 style={{margin:'3px 0'}}>Build Plans</h1></div></div><p>Build the plan, edit the estimate if needed, review it, then move directly into contract signing and job start.</p></section>
  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:14,padding:20,border:'1px solid #d9deea',borderRadius:16}}><label>Customer<input style={input} value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Optional"/></label><label>Project name<input style={input} value={project} onChange={e=>setProject(e.target.value)} placeholder="12 x 24 shed"/></label><label style={{gridColumn:'1/-1'}}>Describe what is being built<textarea style={{...input,minHeight:110}} value={description} onChange={e=>setDescription(e.target.value)}/></label><label style={{gridColumn:'1/-1'}}>Measurements / field notes<textarea style={{...input,minHeight:80}} value={measurements} onChange={e=>setMeasurements(e.target.value)}/></label><label>Labor rate per hour<input style={input} type="number" min="0" value={laborRate} onChange={e=>setLaborRate(e.target.value)}/></label><div style={{display:'flex',alignItems:'end'}}><button style={primary} disabled={!project.trim()||!description.trim()||working} onClick={generate}><Sparkles size={17}/>{working?' Building plan…':' Generate Build Plan'}</button></div></section>
  {error&&<p style={{padding:14,border:'1px solid #d7a6a6',borderRadius:12}}>{error}</p>}{saved&&<p style={{fontWeight:800}}>{saved}</p>}
  {plan&&<section style={{marginTop:24,padding:22,border:'1px solid #d9deea',borderRadius:16}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><small>BUILD PLAN — VERIFY FIELD CONDITIONS</small><h2>{plan.title}</h2>{editing?<textarea style={{...input,minHeight:80}} value={plan.overview} onChange={e=>{setEstimateReviewed(false);setPlan({...plan,overview:e.target.value})}}/>:<p>{plan.overview}</p>}</div><div style={{fontSize:26,fontWeight:900}}>{money(plan.estimatedTotalCost)}</div></div>
   <h3><ListChecks size={18}/> How to Build</h3><ol>{plan.steps.map((x,i)=><li key={i}>{x}</li>)}</ol>
   <h3><PackageCheck size={18}/> Supply List</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={th}>Item</th><th style={th}>Quantity</th><th style={th}>Est. Unit</th><th style={th}>Est. Cost</th>{editing&&<th style={th}>Remove</th>}</tr></thead><tbody>{plan.supplies.map((s,i)=><tr key={i}><td style={td}>{editing?<input style={smallInput} value={s.item} onChange={e=>changeSupply(i,'item',e.target.value)}/>:s.item}</td><td style={td}>{editing?<input style={smallInput} value={s.quantity} onChange={e=>changeSupply(i,'quantity',e.target.value)}/>:s.quantity}</td><td style={td}>{editing?<input style={smallInput} type="number" min="0" value={s.estimatedUnitCost} onChange={e=>changeSupply(i,'estimatedUnitCost',e.target.value)}/>:money(s.estimatedUnitCost)}</td><td style={td}>{editing?<input style={smallInput} type="number" min="0" value={s.estimatedLineCost} onChange={e=>changeSupply(i,'estimatedLineCost',e.target.value)}/>:money(s.estimatedLineCost)}</td>{editing&&<td style={td}><button style={icon} onClick={()=>removeSupply(i)}><Trash2 size={15}/></button></td>}</tr>)}</tbody></table></div>
   {editing&&<button style={{...primary,marginTop:12,background:'#eef2f7',color:'#172033'}} onClick={addSupply}><Plus size={16}/> Add Specific Item</button>}
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,margin:'20px 0'}}><Cost label="Estimated materials" value={plan.materialCost}/>{editing?<div style={costBox}><small>Labor hours</small><input style={input} type="number" min="0" value={plan.estimatedLaborHours} onChange={e=>changeLabor('estimatedLaborHours',e.target.value)}/></div>:<Cost label={`Labor (${plan.estimatedLaborHours} hrs)`} value={plan.laborCost}/>} {editing?<div style={costBox}><small>Labor cost</small><input style={input} type="number" min="0" value={plan.laborCost} onChange={e=>changeLabor('laborCost',e.target.value)}/></div>:null}<Cost label="Estimated total" value={plan.estimatedTotalCost}/></div>
   <div style={{padding:14,border:'1px solid #d9deea',borderRadius:12,marginBottom:14,background:'#f8fafc'}}><label style={{display:'flex',gap:10,alignItems:'flex-start',fontWeight:800,cursor:'pointer'}}><input type="checkbox" checked={estimateReviewed} onChange={e=>setEstimateReviewed(e.target.checked)} style={{width:20,height:20,marginTop:1}}/><span>I have reviewed this estimate and it is edited to my liking.<small style={{display:'block',fontWeight:500,marginTop:4}}>Check this box when the materials, quantities, labor, and total are ready for the contract.</small></span></label></div>
   <div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button style={{...primary,background:editing?'#16794b':'#eef2f7',color:editing?'white':'#172033'}} onClick={()=>setEditing(!editing)}><Pencil size={17}/>{editing?' Done Editing':' Edit Estimate'}</button><button style={primary} onClick={savePlan}>Save Build Plan</button><button style={{...primary,background:'#f4a622',color:'#111827',opacity:estimateReviewed?1:.65}} disabled={working} onClick={()=>estimateReviewed?startJob():setError('Please check the estimate review box before approval.')}><Play size={17}/> Approve Estimate & Start Job</button></div>
   <p style={{fontSize:13,opacity:.75}}>{editing?'Keep editing as needed. When everything looks right, check the review box before approval.':'The approval button stays available. If the estimate is changed later, the review box resets so it can be checked again.'}</p>
  </section>}
  <section style={{marginTop:30}}><h2>Saved Build Plans</h2>{savedPlans.length===0?<p>No build plans saved yet.</p>:savedPlans.map(p=><div key={p.id} style={{display:'flex',justifyContent:'space-between',padding:15,border:'1px solid #d9deea',borderRadius:12,marginBottom:10}}><div><b>{p.title}</b><div>{p.customer||'No customer'} · {money(p.estimatedTotalCost)}</div></div><button style={icon} onClick={()=>removePlan(p.id)}><Trash2 size={17}/></button></div>)}</section>
 </main>
}
function Cost({label,value}:{label:string,value:number}){return <div style={costBox}><small>{label}</small><div style={{fontSize:22,fontWeight:900}}>{money(value)}</div></div>}
const input={display:'block',boxSizing:'border-box' as const,width:'100%',marginTop:7,padding:'11px 12px',border:'1px solid #cfd5df',borderRadius:10,font:'inherit'}
const smallInput={...input,minWidth:100,marginTop:0,padding:'8px 9px'}
const primary={display:'inline-flex',alignItems:'center',justifyContent:'center',gap:8,padding:'12px 16px',border:0,borderRadius:10,fontWeight:800,cursor:'pointer',background:'#172033',color:'white'}
const icon={display:'inline-flex',padding:9,border:'1px solid #d9deea',borderRadius:9,background:'white',cursor:'pointer'}
const costBox={padding:14,border:'1px solid #d9deea',borderRadius:12}
const th={textAlign:'left' as const,padding:'10px 8px',borderBottom:'2px solid #d9deea'}
const td={padding:'10px 8px',borderBottom:'1px solid #e5e8ef'}