'use client'

import { useState } from 'react'
import { CheckCircle2,Download,FileSignature,PenLine } from 'lucide-react'

type Doc={id:number;type:string;customer:string;project:string;status:string;content?:string;approvedAt?:string;signature?:string;contractorSignature?:string;customerSignature?:string;contractDate?:string}
type Data={docs:Doc[];settings:{businessName:string;phone:string;email:string;address:string;estimateTerms:string};[key:string]:any}

const esc=(value:string)=>value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')

export default function FormalContract({doc,data,setData}:{doc:Doc,data:Data,setData:(d:any)=>void}){
 const [contractor,setContractor]=useState(doc.contractorSignature||''),[customer,setCustomer]=useState(doc.customerSignature||doc.signature||''),[downloadMessage,setDownloadMessage]=useState('')
 const signed=!!(doc.contractorSignature&&doc.customerSignature)
 function execute(){if(!contractor.trim()||!customer.trim())return;const now=new Date().toISOString();setData({...data,docs:data.docs.map(d=>d.id===doc.id?{...d,status:'Executed Contract',contractorSignature:contractor.trim(),customerSignature:customer.trim(),signature:customer.trim(),contractDate:now,approvedAt:now}:d)})}
 function downloadPdf(){
  if(!signed)return
  setDownloadMessage('Opening the signed contract…')
  const title=`${doc.project||'Construction Agreement'} — Signed Contract`
  const body=esc(doc.content||'').replace(/\n/g,'<br/>')
  const terms=data.settings.estimateTerms?`<section><h3>Terms</h3><p>${esc(data.settings.estimateTerms)}</p></section>`:''
  const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;max-width:800px;margin:0 auto;padding:36px;line-height:1.5}h1{margin-bottom:4px}.muted{color:#667085}.contract{border-top:1px solid #d9deea;border-bottom:1px solid #d9deea;padding:22px 0;margin:22px 0}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:28px;margin-top:30px}.sig{border-top:1px solid #172033;padding-top:8px}.seal{margin-top:30px;padding:14px;border:1px solid #8ac7a5;background:#f1fbf5;border-radius:10px}.actions{margin:0 0 24px}.actions button{font:inherit;font-weight:800;padding:12px 16px;border:0;border-radius:10px;background:#172033;color:#fff}@media(max-width:600px){body{padding:20px}.signatures{grid-template-columns:1fr}}@media print{body{max-width:none;padding:0}.actions{display:none}}</style></head><body><div class="actions"><button onclick="window.print()">Save / Print PDF</button></div><h1>${esc(doc.project||'Construction Agreement')}</h1><div class="muted">Executed Contract</div><p><b>Contractor:</b> ${esc(data.settings.businessName||'Contractor')}<br/><span class="muted">${esc([data.settings.address,data.settings.phone,data.settings.email].filter(Boolean).join(' · '))}</span></p><p><b>Customer:</b> ${esc(doc.customer||'Customer named in agreement')}</p><div class="contract">${body}</div>${terms}<div class="signatures"><div class="sig"><b>Contractor signature</b><br/>${esc(doc.contractorSignature||'')}</div><div class="sig"><b>Customer signature</b><br/>${esc(doc.customerSignature||'')}</div></div><div class="seal"><b>Signed Contract</b><br/>Executed ${doc.contractDate?esc(new Date(doc.contractDate).toLocaleString()):''}</div></body></html>`
  const url='data:text/html;charset=utf-8,'+encodeURIComponent(html)
  const opened=window.open(url,'_blank')
  if(!opened){window.location.href=url;return}
  setDownloadMessage('Signed contract opened. Tap Save / Print PDF, then save it to Files from the iPhone print/share screen.')
 }
 return <div className={signed?'formalContract executed':'formalContract'}><div className="contractTitle"><FileSignature/><div><small>{signed?'EXECUTED CONTRACT':'CONTRACT APPROVAL'}</small><h3>{doc.project||'Construction Agreement'}</h3></div></div><div className="contractParty"><b>Contractor</b><span>{data.settings.businessName||'Contractor'}</span><small>{[data.settings.address,data.settings.phone,data.settings.email].filter(Boolean).join(' · ')}</small></div><div className="contractParty"><b>Customer</b><span>{doc.customer||'Customer named in agreement'}</span></div><div className="contractBody"><pre>{doc.content}</pre></div>{data.settings.estimateTerms&&<div className="contractTerms"><b>Terms</b><p>{data.settings.estimateTerms}</p></div>}<div className="signatureGrid"><label><span>Contractor signature</span><input aria-label="Contractor signature" value={contractor} disabled={signed} onChange={e=>setContractor(e.target.value)} placeholder="Type full legal name"/>{signed&&<small>Signed: {doc.contractorSignature}</small>}</label><label><span>Customer signature</span><input aria-label="Customer signature" value={customer} disabled={signed} onChange={e=>setCustomer(e.target.value)} placeholder="Customer types full legal name"/>{signed&&<small>Signed: {doc.customerSignature}</small>}</label></div>{signed?<><div className="executedSeal"><CheckCircle2/><div><b>Signed Contract</b><span>Executed {doc.contractDate?new Date(doc.contractDate).toLocaleString():''}</span></div></div><button type="button" className="primary noPrint" onClick={downloadPdf}><Download size={16}/> Open Signed Contract PDF</button>{downloadMessage&&<p className="noPrint" style={{fontWeight:700}}>{downloadMessage}</p>}</>:<button type="button" className="primary" disabled={!contractor.trim()||!customer.trim()} onClick={execute}><PenLine size={16}/> Sign & Create Formal Contract</button>}<p className="contractNotice">Electronic names are recorded with this contract and execution date. Parties should review the complete agreement before signing.</p></div>
}
