'use client'

import { useState } from 'react'
import { CheckCircle2,Download,FileSignature,PenLine } from 'lucide-react'

type Doc={id:number;type:string;customer:string;project:string;status:string;content?:string;approvedAt?:string;signature?:string;contractorSignature?:string;customerSignature?:string;contractDate?:string}
type Data={docs:Doc[];settings:{businessName:string;phone:string;email:string;address:string;estimateTerms:string};[key:string]:any}

export default function FormalContract({doc,data,setData}:{doc:Doc,data:Data,setData:(d:any)=>void}){
 const [contractor,setContractor]=useState(doc.contractorSignature||''),[customer,setCustomer]=useState(doc.customerSignature||doc.signature||'')
 const signed=!!(doc.contractorSignature&&doc.customerSignature)
 function execute(){if(!contractor.trim()||!customer.trim())return;const now=new Date().toISOString();setData({...data,docs:data.docs.map(d=>d.id===doc.id?{...d,status:'Executed Contract',contractorSignature:contractor.trim(),customerSignature:customer.trim(),signature:customer.trim(),contractDate:now,approvedAt:now}:d)})}
 return <div className={signed?'formalContract executed':'formalContract'}><div className="contractTitle"><FileSignature/><div><small>{signed?'EXECUTED CONTRACT':'CONTRACT APPROVAL'}</small><h3>{doc.project||'Construction Agreement'}</h3></div></div><div className="contractParty"><b>Contractor</b><span>{data.settings.businessName||'Contractor'}</span><small>{[data.settings.address,data.settings.phone,data.settings.email].filter(Boolean).join(' · ')}</small></div><div className="contractParty"><b>Customer</b><span>{doc.customer||'Customer named in agreement'}</span></div><div className="contractBody"><pre>{doc.content}</pre></div>{data.settings.estimateTerms&&<div className="contractTerms"><b>Terms</b><p>{data.settings.estimateTerms}</p></div>}<div className="signatureGrid"><label><span>Contractor signature</span><input aria-label="Contractor signature" value={contractor} disabled={signed} onChange={e=>setContractor(e.target.value)} placeholder="Type full legal name"/>{signed&&<small>Signed: {doc.contractorSignature}</small>}</label><label><span>Customer signature</span><input aria-label="Customer signature" value={customer} disabled={signed} onChange={e=>setCustomer(e.target.value)} placeholder="Customer types full legal name"/>{signed&&<small>Signed: {doc.customerSignature}</small>}</label></div>{signed?<><div className="executedSeal"><CheckCircle2/><div><b>Signed Contract</b><span>Executed {doc.contractDate?new Date(doc.contractDate).toLocaleString():''}</span></div></div><button className="primary noPrint" onClick={()=>window.print()}><Download size={16}/> Download / Print Contract PDF</button></>:<button className="primary" disabled={!contractor.trim()||!customer.trim()} onClick={execute}><PenLine size={16}/> Sign & Create Formal Contract</button>}<p className="contractNotice">Electronic names are recorded with this contract and execution date. Parties should review the complete agreement before signing.</p></div>
}
