'use client'

import { useMemo,useState } from 'react'
import { BriefcaseBusiness,Clock3,Download,Play,Plus,Receipt,Trash2,X } from 'lucide-react'

type Project={id:number;customer:string;name:string;status:string;date:string;amount:number}
type Expense={id:number;merchant:string;amount:number;project:string;category:string;date:string;color?:string}
type Labor={id:number;employee:string;hours:number;rate:number;gross:number;status:string;date:string;project?:string}
type Settings={businessName:string;phone:string;email:string;address:string;estimateTerms:string}
type Data={projects:Project[];receipts:Expense[];payroll:Labor[];settings:Settings;[key:string]:any}

const money=(n:number)=>'$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})

export default function JobTracker({project,data,setData,onClose}:{project:Project,data:Data,setData:(d:any)=>void,onClose:()=>void}){
 const [merchant,setMerchant]=useState(''),[expenseAmount,setExpenseAmount]=useState(''),[category,setCategory]=useState('Materials')
 const [employee,setEmployee]=useState(''),[hours,setHours]=useState(''),[rate,setRate]=useState('')
 const expenses=useMemo(()=>data.receipts.filter(r=>r.project.trim().toLowerCase()===project.name.trim().toLowerCase()),[data.receipts,project.name])
 const labor=useMemo(()=>data.payroll.filter(p=>(p.project||'').trim().toLowerCase()===project.name.trim().toLowerCase()),[data.payroll,project.name])
 const expenseTotal=expenses.reduce((s,x)=>s+Number(x.amount||0),0),laborHours=labor.reduce((s,x)=>s+Number(x.hours||0),0),laborTotal=labor.reduce((s,x)=>s+Number(x.gross||0),0),actual=expenseTotal+laborTotal,variance=Number(project.amount||0)-actual
 function startJob(){setData({...data,projects:data.projects.map(p=>p.id===project.id?{...p,status:'In Progress',date:p.date==='Not scheduled'?new Date().toISOString().slice(0,10):p.date}:p)})}
 function addExpense(){if(!merchant.trim()||Number(expenseAmount)<=0)return;setData({...data,receipts:[{id:Date.now(),merchant:merchant.trim(),amount:Number(expenseAmount),project:project.name,category,date:new Date().toISOString().slice(0,10),color:'#f4a622'},...data.receipts]});setMerchant('');setExpenseAmount('')}
 function addLabor(){const h=Number(hours),r=Number(rate);if(!employee.trim()||h<=0)return;setData({...data,payroll:[{id:Date.now(),employee:employee.trim(),hours:h,rate:r,gross:h*r,status:'Recorded',date:new Date().toISOString().slice(0,10),project:project.name},...data.payroll]});setEmployee('');setHours('');setRate('')}
 function printPdf(){window.print()}
 return <div className="workspace jobTracker"><div className="workspaceHead noPrint"><div><small>ACTIVE JOB</small><h2>{project.name}</h2><p>{project.customer} · Track job costs and labor as the work happens.</p></div><button className="ghost" onClick={onClose}><X size={16}/> Close</button></div>
 <div className="reviewActions noPrint">{project.status!=='In Progress'&&<button className="primary" onClick={startJob}><Play size={16}/> Start Job</button>}<button className="primary" onClick={printPdf}><Download size={16}/> Download / Print PDF</button></div>
 <section className="jobReport" id="job-cost-report"><div className="jobReportHeader"><div><div className="jobReportBrand"><BriefcaseBusiness size={28}/><div><strong>{data.settings.businessName||'BuildFlow Contractor'}</strong><span>JOB COST REPORT</span></div></div><p>{[data.settings.address,data.settings.phone,data.settings.email].filter(Boolean).join(' · ')}</p></div><div className="jobReportMeta"><b>{project.name}</b><span>Customer: {project.customer}</span><span>Status: {project.status}</span><span>Report date: {new Date().toLocaleDateString()}</span></div></div>
 <div className="jobTotals"><div><span>Original Estimate</span><strong>{money(project.amount)}</strong></div><div><span>Expenses</span><strong>{money(expenseTotal)}</strong></div><div><span>Labor</span><strong>{laborHours.toFixed(2)} hrs · {money(laborTotal)}</strong></div><div><span>Total Job Cost</span><strong>{money(actual)}</strong></div><div><span>Estimate Remaining</span><strong>{money(variance)}</strong></div></div>
 <h3>Job Expenses</h3>{expenses.length?<table><thead><tr><th>Date</th><th>Vendor / Description</th><th>Category</th><th>Amount</th></tr></thead><tbody>{expenses.map(x=><tr key={x.id}><td>{x.date||'—'}</td><td>{x.merchant}</td><td>{x.category}</td><td>{money(x.amount)}</td></tr>)}</tbody></table>:<p>No job expenses recorded.</p>}
 <h3>Labor Hours</h3>{labor.length?<table><thead><tr><th>Date</th><th>Worker</th><th>Hours</th><th>Rate</th><th>Labor Cost</th></tr></thead><tbody>{labor.map(x=><tr key={x.id}><td>{x.date||'—'}</td><td>{x.employee}</td><td>{x.hours}</td><td>{money(x.rate)}/hr</td><td>{money(x.gross)}</td></tr>)}</tbody></table>:<p>No labor recorded.</p>}
 <div className="jobReportFooter">Prepared by {data.settings.businessName||'Contractor'} · BuildFlow HQ</div></section>
 <section className="grid lower noPrint"><div className="card"><div className="cardhead"><h3><Receipt size={17}/> Add Job Expense</h3></div><div className="builderGrid"><label>Vendor / description<input value={merchant} onChange={e=>setMerchant(e.target.value)} placeholder="Lumber yard, fuel, permit..."/></label><label>Amount<input type="number" min="0" step="0.01" value={expenseAmount} onChange={e=>setExpenseAmount(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>Materials</option><option>Tools</option><option>Fuel</option><option>Subcontractor</option><option>Permit</option><option>Other</option></select></label><button className="primary" disabled={!merchant.trim()||Number(expenseAmount)<=0} onClick={addExpense}><Plus size={16}/> Add Expense</button></div></div>
 <div className="card"><div className="cardhead"><h3><Clock3 size={17}/> Add Labor</h3></div><div className="builderGrid"><label>Worker<input value={employee} onChange={e=>setEmployee(e.target.value)} placeholder="Employee or subcontractor"/></label><label>Hours<input type="number" min="0" step="0.25" value={hours} onChange={e=>setHours(e.target.value)}/></label><label>Hourly rate<input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label><button className="primary" disabled={!employee.trim()||Number(hours)<=0} onClick={addLabor}><Plus size={16}/> Add Labor</button></div></div></section>
 <div className="noPrint">{expenses.map(x=><div className="wideRow" key={'e'+x.id}><Receipt size={18}/><div className="grow"><b>{x.merchant}</b><span>{x.category} · {x.date}</span></div><strong>{money(x.amount)}</strong><button className="iconButton" aria-label="Delete expense" onClick={()=>setData({...data,receipts:data.receipts.filter(r=>r.id!==x.id)})}><Trash2 size={15}/></button></div>)}{labor.map(x=><div className="wideRow" key={'l'+x.id}><Clock3 size={18}/><div className="grow"><b>{x.employee}</b><span>{x.hours} hrs × {money(x.rate)}</span></div><strong>{money(x.gross)}</strong><button className="iconButton" aria-label="Delete labor" onClick={()=>setData({...data,payroll:data.payroll.filter(p=>p.id!==x.id)})}><Trash2 size={15}/></button></div>)}</div></div>
}
