import { chromium } from 'playwright';
const base=process.env.BASE_URL||'https://build-flowhq2.vercel.app';
const stamp=Date.now(), email=`buildflow.e2e.${stamp}@example.com`, password=`BuildFlow!${String(stamp).slice(-8)}`, company=`BuildFlow E2E ${stamp}`;
const failures=[],consoleErrors=[],apiFailures=[];
const browser=await chromium.launch({headless:true}); const context=await browser.newContext({viewport:{width:1440,height:1000}}); const page=await context.newPage();
page.on('pageerror',e=>failures.push(`pageerror: ${e.message}`)); page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())}); page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=500&&!r.url().includes('/api/ai'))apiFailures.push(`${r.status()} ${r.request().method()} ${r.url()}`)});
async function snap(n){await page.screenshot({path:`test-results/${n}.png`,fullPage:true})}
async function clickButton(rx){const b=page.getByRole('button',{name:rx}).last();await b.waitFor({state:'visible',timeout:5000});await b.click();await page.waitForTimeout(150)}
async function fillLabel(rx,v){const x=page.getByLabel(rx).last();await x.waitFor({state:'visible',timeout:5000});await x.fill(v)}
try{
 console.log(`TEST base=${base}`);await page.goto(base,{waitUntil:'networkidle',timeout:60000});if(!page.url().includes('/login'))throw new Error(`Expected /login, got ${page.url()}`);console.log('PASS redirect');
 const aiProbe=await page.evaluate(async()=>{const r=await fetch('/api/ai',{method:'POST',redirect:'manual',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'estimate',input:'Project: Deployment probe\nJob description: Replace 8 feet of baseboard.'})});return{status:r.status,body:await r.text()}});console.log(`AI probe status=${aiProbe.status} body=${aiProbe.body.slice(0,200)}`);if(aiProbe.status!==401&&aiProbe.status!==200)throw new Error(`AI POST route unavailable ${aiProbe.status}: ${aiProbe.body.slice(0,200)}`);if(aiProbe.status===401&&!/AUTH_REQUIRED/.test(aiProbe.body))throw new Error(`AI auth response malformed: ${aiProbe.body.slice(0,200)}`);console.log('PASS protected AI POST route');
 await clickButton(/New to Construction HQ\? Create a company/i);await fillLabel(/Company name/i,company);await fillLabel(/^Email$/i,email);await fillLabel(/^Password$/i,password);await clickButton(/Create Company/i);
 await page.waitForFunction(()=>{const t=document.body.innerText.toLowerCase();const creating=t.includes('creating...');const subscription=location.pathname.includes('/subscribe');const confirmation=/confirm|verification|verify|check.*email|email.*sent/.test(t);const signIn=/\bsign in\b/.test(t);return subscription||confirmation||(!creating&&signIn)},null,{timeout:30000});
 console.log(`PASS signup settled=${page.url()}`);
 // E2E accounts are isolated and allowed through the subscription gate by middleware.
 if(!page.url().includes('/')) await page.goto(base,{waitUntil:'networkidle'});
 await page.goto(base,{waitUntil:'networkidle',timeout:60000});
 if(page.url().includes('/subscribe')) throw new Error('E2E account is still blocked by subscription gate');
 if(page.url().includes('/login')) throw new Error('E2E account lost authentication');
 console.log('PASS authenticated workspace');
 const navButtons=['Home','Jobs','Estimate','Invoices','More'];
 for(const name of navButtons){const b=page.getByRole('button',{name:new RegExp('^'+name+'
 if(page.url().includes('/subscribe')){console.log('PASS subscription onboarding redirect');await snap('production-subscription-gate');}
 else {const body=(await page.locator('body').innerText()).toLowerCase();const confirmation=/confirm|verification|verify|check.*email|email.*sent/.test(body);const creating=body.includes('creating...');const signInText=/\bsign in\b/.test(body);if(confirmation){console.log('PASS signup email-confirmation flow');await snap('production-email-confirmation');}else if(!creating&&signInText){console.log('PASS signup returned to sign-in-ready flow');await snap('production-signin-ready');}else throw new Error(`Signup did not settle into a valid onboarding state: ${body.slice(0,500)}`);}
}catch(e){failures.push(e?.stack||String(e));try{await snap('production-smoke-failure')}catch{}}finally{await browser.close()}
for(const e of consoleErrors)console.log(`CONSOLE_ERROR ${e}`);for(const e of apiFailures)console.log(`HTTP_FAILURE ${e}`);if(consoleErrors.some(x=>!/favicon|hydration|401|400|429/i.test(x)))failures.push(...consoleErrors.filter(x=>!/favicon|hydration|401|400|429/i.test(x)).map(x=>`console: ${x}`));if(apiFailures.length)failures.push(...apiFailures.map(x=>`http: ${x}`));if(failures.length){console.error('\nPRODUCTION SMOKE FAILED');failures.forEach(x=>console.error(x));process.exit(1)}console.log('\nPRODUCTION SMOKE PASSED');
,'i')}).first();await b.waitFor({state:'visible',timeout:5000});await b.click();await page.waitForTimeout(120);console.log('PASS click '+name)}
 // Open More and click each tool that stays inside the SPA. Billing is intentionally excluded because it navigates to subscription management.
 await page.getByRole('button',{name:/^More$/i}).first().click();await page.waitForTimeout(100);
 const tools=['Schedule','Customers','Contact Book','Contracts','Change Orders','Plans Studio','Receipts','Before & After','Documents','Notes','Settings'];
 for(const name of tools){let b=page.getByRole('button',{name:new RegExp('^'+name+'
 if(page.url().includes('/subscribe')){console.log('PASS subscription onboarding redirect');await snap('production-subscription-gate');}
 else {const body=(await page.locator('body').innerText()).toLowerCase();const confirmation=/confirm|verification|verify|check.*email|email.*sent/.test(body);const creating=body.includes('creating...');const signInText=/\bsign in\b/.test(body);if(confirmation){console.log('PASS signup email-confirmation flow');await snap('production-email-confirmation');}else if(!creating&&signInText){console.log('PASS signup returned to sign-in-ready flow');await snap('production-signin-ready');}else throw new Error(`Signup did not settle into a valid onboarding state: ${body.slice(0,500)}`);}
}catch(e){failures.push(e?.stack||String(e));try{await snap('production-smoke-failure')}catch{}}finally{await browser.close()}
for(const e of consoleErrors)console.log(`CONSOLE_ERROR ${e}`);for(const e of apiFailures)console.log(`HTTP_FAILURE ${e}`);if(consoleErrors.some(x=>!/favicon|hydration|401|400|429/i.test(x)))failures.push(...consoleErrors.filter(x=>!/favicon|hydration|401|400|429/i.test(x)).map(x=>`console: ${x}`));if(apiFailures.length)failures.push(...apiFailures.map(x=>`http: ${x}`));if(failures.length){console.error('\nPRODUCTION SMOKE FAILED');failures.forEach(x=>console.error(x));process.exit(1)}console.log('\nPRODUCTION SMOKE PASSED');
,'i')}).first();await b.waitFor({state:'visible',timeout:5000});await b.click();await page.waitForTimeout(120);console.log('PASS tool '+name);await page.getByRole('button',{name:/^More$/i}).first().click();await page.waitForTimeout(80)}
 // Functional create/delete checks on isolated data.
 await page.getByRole('button',{name:/^Jobs$/i}).first().click();await fillLabel(/Customer \/ new customer/i,'E2E Customer');await fillLabel(/^Project$/i,'E2E Project');await fillLabel(/Estimate \/ budget/i,'1250');await clickButton(/Create Customer Project Folder/i);console.log('PASS create project');
 await page.getByRole('button',{name:/^Invoices$/i}).first().click();await fillLabel(/^Customer \*/i,'E2E Customer');const proj=page.getByLabel(/^Project$/i).last();await proj.selectOption({label:/E2E Customer.*E2E Project/});const desc=page.getByPlaceholder('Detailed work or material').last();await desc.fill('Removed brush and leveled ground');const rate=page.getByLabel('Rate').last();await rate.fill('1250');await clickButton(/Create & Save Invoice/i);await page.waitForFunction(()=>document.body.innerText.includes('saved successfully'),null,{timeout:10000});console.log('PASS create/save invoice');
 await page.getByRole('button',{name:/^More$/i}).first().click();await page.getByRole('button',{name:/^Notes$/i}).first().click();await page.getByPlaceholder(/Follow-up, material reminder/i).fill('E2E troubleshooting note');await clickButton(/Save Note/i);if(!document.body.innerText.includes('E2E troubleshooting note'))throw new Error('Note save did not render');console.log('PASS save note');
 await snap('authenticated-full-troubleshoot');
 if(page.url().includes('/subscribe')){console.log('PASS subscription onboarding redirect');await snap('production-subscription-gate');}
 else {const body=(await page.locator('body').innerText()).toLowerCase();const confirmation=/confirm|verification|verify|check.*email|email.*sent/.test(body);const creating=body.includes('creating...');const signInText=/\bsign in\b/.test(body);if(confirmation){console.log('PASS signup email-confirmation flow');await snap('production-email-confirmation');}else if(!creating&&signInText){console.log('PASS signup returned to sign-in-ready flow');await snap('production-signin-ready');}else throw new Error(`Signup did not settle into a valid onboarding state: ${body.slice(0,500)}`);}
}catch(e){failures.push(e?.stack||String(e));try{await snap('production-smoke-failure')}catch{}}finally{await browser.close()}
for(const e of consoleErrors)console.log(`CONSOLE_ERROR ${e}`);for(const e of apiFailures)console.log(`HTTP_FAILURE ${e}`);if(consoleErrors.some(x=>!/favicon|hydration|401|400|429/i.test(x)))failures.push(...consoleErrors.filter(x=>!/favicon|hydration|401|400|429/i.test(x)).map(x=>`console: ${x}`));if(apiFailures.length)failures.push(...apiFailures.map(x=>`http: ${x}`));if(failures.length){console.error('\nPRODUCTION SMOKE FAILED');failures.forEach(x=>console.error(x));process.exit(1)}console.log('\nPRODUCTION SMOKE PASSED');
