import { chromium } from 'playwright';
const base=process.env.BASE_URL||'https://build-flowhq2.vercel.app';
const stamp=Date.now(), email=`buildflow.e2e.${stamp}@example.com`, password=`BuildFlow!${String(stamp).slice(-8)}`, company=`BuildFlow E2E ${stamp}`;
const failures=[],consoleErrors=[],apiFailures=[];
const browser=await chromium.launch({headless:true}); const context=await browser.newContext({viewport:{width:1440,height:1000}}); const page=await context.newPage();
page.on('pageerror',e=>failures.push(`pageerror: ${e.message}`)); page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())}); page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=500&&!r.url().includes('/api/ai'))apiFailures.push(`${r.status()} ${r.request().method()} ${r.url()}`)});
async function snap(n){await page.screenshot({path:`test-results/${n}.png`,fullPage:true})}
async function clickButton(rx){const b=page.getByRole('button',{name:rx}).last();await b.waitFor({state:'visible',timeout:5000});await b.click();await page.waitForTimeout(150)}
async function fillLabel(rx,v){const x=page.getByLabel(rx).last();await x.waitFor({state:'visible',timeout:5000});await x.fill(v)}
try{
 console.log(`TEST base=${base}`);await page.goto(base,{waitUntil:'networkidle',timeout:60000});if(!page.url().includes('/login'))throw new Error(`Expected /login, got ${page.url()}`);console.log('PASS redirect');
 const aiResult=await page.evaluate(async()=>{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'estimate',input:'Customer: E2E\nProject: Repair\nJob description: Replace 8 feet of damaged baseboard and paint to match.'})});return{status:r.status,body:await r.text()}});console.log(`AI status=${aiResult.status} body=${aiResult.body.slice(0,250)}`);if(aiResult.status!==200)throw new Error(`Live AI estimate failed ${aiResult.status}: ${aiResult.body.slice(0,200)}`);const parsed=JSON.parse(aiResult.body);if(!parsed.result?.materials||!parsed.result?.labor||typeof parsed.result?.amount!=='number')throw new Error('AI estimate response missing launch-critical estimate fields');console.log(`PASS live AI estimate provider=${parsed.provider||'unknown'} amount=${parsed.result.amount}`);
 await clickButton(/New to BuildFlow\? Create a company/i);await fillLabel(/Company name/i,company);await fillLabel(/^Email$/i,email);await fillLabel(/^Password$/i,password);await clickButton(/Create Company/i);await page.waitForURL(u=>u.pathname.includes('/subscribe')||u.pathname.includes('/login'),{timeout:30000});console.log(`PASS signup destination=${page.url()}`);
 if(page.url().includes('/subscribe')){console.log('PASS subscription onboarding redirect');await snap('production-subscription-gate');}
 else {const body=(await page.locator('body').innerText()).toLowerCase();const confirmation=/confirm|verification|verify|check.*email|email.*sent/.test(body);const signIn=await page.getByRole('button',{name:/^Sign In$/i}).count();if(confirmation){console.log('PASS signup email-confirmation flow');await snap('production-email-confirmation');}else if(signIn){console.log('PASS signup returned to sign-in flow');await snap('production-signin-ready');}else throw new Error(`Signup returned to login without confirmation or sign-in UI: ${body.slice(0,500)}`);}
}catch(e){failures.push(e?.stack||String(e));try{await snap('production-smoke-failure')}catch{}}finally{await browser.close()}
for(const e of consoleErrors)console.log(`CONSOLE_ERROR ${e}`);for(const e of apiFailures)console.log(`HTTP_FAILURE ${e}`);if(consoleErrors.some(x=>!/favicon|hydration/i.test(x)))failures.push(...consoleErrors.map(x=>`console: ${x}`));if(apiFailures.length)failures.push(...apiFailures.map(x=>`http: ${x}`));if(failures.length){console.error('\nPRODUCTION SMOKE FAILED');failures.forEach(x=>console.error(x));process.exit(1)}console.log('\nPRODUCTION SMOKE PASSED');
