import { chromium } from 'playwright';

const base=process.env.BASE_URL||'https://build-flowhq2.vercel.app';
const stamp=Date.now(), marker=`E2E-${stamp}`, email=`buildflow.e2e.${stamp}@example.com`, password=`BuildFlow!${String(stamp).slice(-8)}`, company=`BuildFlow E2E ${stamp}`;
const failures=[],consoleErrors=[],apiFailures=[];
const browser=await chromium.launch({headless:true}); const context=await browser.newContext({viewport:{width:1440,height:1000}}); const page=await context.newPage();
page.on('pageerror',e=>failures.push(`pageerror: ${e.message}`)); page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())}); page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400&&!r.url().includes('/api/ai'))apiFailures.push(`${r.status()} ${r.request().method()} ${r.url()}`)});
async function snap(n){await page.screenshot({path:`test-results/${n}.png`,fullPage:true})}
async function nav(n){await page.getByRole('button',{name:new RegExp(`^${n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`,'i')}).first().click();await page.waitForTimeout(150)}
async function clickButton(rx){const b=page.getByRole('button',{name:rx}).last();await b.waitFor({state:'visible',timeout:5000});await b.click();await page.waitForTimeout(100)}
async function clickFormAction(opener){const buttons=await page.locator('main button:visible').evaluateAll(els=>els.map((e,i)=>({i,text:(e.textContent||'').trim(),disabled:e.disabled})));console.log(`FORM buttons=${JSON.stringify(buttons)}`);let candidate=buttons.filter(b=>!b.disabled&&b.text!==opener&&!/^AI Estimate$/i.test(b.text)&&!/delete|trash|close|cancel/i.test(b.text)&&/save|create|add|record/i.test(b.text)).at(-1);if(!candidate)candidate=buttons.filter(b=>!b.disabled&&b.text!==opener&&!/^AI Estimate$/i.test(b.text)&&!/delete|trash|close|cancel/i.test(b.text)).at(-1);if(!candidate)throw new Error(`No form submit candidate after ${opener}`);await page.locator('main button:visible').nth(candidate.i).click();await page.waitForTimeout(180)}
async function fillLabel(rx,v){const x=page.getByLabel(rx).last();await x.waitFor({state:'visible',timeout:5000});const tag=await x.evaluate(el=>el.tagName.toLowerCase());if(tag==='select'){const opts=await x.locator('option').allTextContents();const wanted=opts.find(o=>o.trim()&&!/^select/i.test(o));if(wanted)await x.selectOption({label:wanted})}else await x.fill(v)}
async function optional(rx,v){const x=page.getByLabel(rx).last();if(await x.count()){const tag=await x.evaluate(el=>el.tagName.toLowerCase());if(tag==='select'){const opts=await x.locator('option').allTextContents();const wanted=opts.find(o=>o.includes(marker))||opts.find(o=>o.trim()&&!/^select/i.test(o));if(wanted)await x.selectOption({label:wanted})}else await x.fill(v)}}
async function expectText(t){await page.getByText(t,{exact:false}).first().waitFor({state:'visible',timeout:7000})}
async function waitSaved(){await page.waitForTimeout(900);const t=await page.locator('.sidefoot').innerText().catch(()=>'');if(/save failed/i.test(t))throw new Error('Workspace autosave failed')}
try{
 console.log(`TEST base=${base}`);await page.goto(base,{waitUntil:'networkidle',timeout:60000});if(!page.url().includes('/login'))throw new Error(`Expected /login, got ${page.url()}`);console.log('PASS redirect');
 await clickButton(/New to BuildFlow\? Create a company/i);await fillLabel(/Company name/i,company);await fillLabel(/^Email$/i,email);await fillLabel(/^Password$/i,password);await clickButton(/Create Company/i);await expectText('Account created');console.log('PASS signup');
 await fillLabel(/^Email$/i,email);await fillLabel(/^Password$/i,password);await clickButton(/^Sign In$/i);await page.waitForURL(u=>!u.pathname.includes('/login'),{timeout:30000});await page.waitForLoadState('networkidle');console.log('PASS sign in');

 await nav('Customers');await clickButton(/Add Customer/i);console.log(`CUSTOMER labels=${JSON.stringify((await page.locator('main label:visible').allTextContents()).map(x=>x.trim()))}`);await fillLabel(/^Name$/i,`${marker} Customer`);await optional(/Phone/i,'9895550101');await optional(/Email/i,`customer.${stamp}@example.com`);await optional(/Address/i,'123 Test Street');await clickFormAction('Add Customer');await expectText(`${marker} Customer`);await waitSaved();console.log('PASS customer create/save');

 await nav('Projects');await clickButton(/New Project/i);console.log(`PROJECT labels=${JSON.stringify((await page.locator('main label:visible').allTextContents()).map(x=>x.trim()))}`);await fillLabel(/Customer/i,`${marker} Customer`);await fillLabel(/Project|Name/i,`${marker} Remodel`);await optional(/Amount|Value|Price/i,'12500');await clickFormAction('New Project');await expectText(`${marker} Remodel`);await waitSaved();console.log('PASS project create/save');

 await nav('Invoices');await clickButton(/New Invoice/i);console.log(`INVOICE labels=${JSON.stringify((await page.locator('main label:visible').allTextContents()).map(x=>x.trim()))}`);await fillLabel(/Customer/i,`${marker} Customer`);await fillLabel(/Project/i,`${marker} Remodel`);await fillLabel(/Amount/i,'3200');await clickFormAction('New Invoice');await expectText(`${marker} Customer`);await clickButton(/Mark Paid/i);await waitSaved();console.log('PASS invoice create/status/save');

 await nav('Receipts');await clickButton(/Add Receipt/i);console.log(`RECEIPT labels=${JSON.stringify((await page.locator('main label:visible').allTextContents()).map(x=>x.trim()))}`);await fillLabel(/Merchant|Vendor/i,`${marker} Supply`);await fillLabel(/Amount/i,'425.75');await optional(/Project/i,`${marker} Remodel`);await optional(/Category/i,'Materials');await optional(/Date/i,'2026-09-09');await clickFormAction('Add Receipt');await expectText(`${marker} Supply`);await waitSaved();console.log('PASS receipt create/save');

 await nav('Schedule');await clickButton(/Add Schedule Item/i);console.log(`SCHEDULE labels=${JSON.stringify((await page.locator('main label:visible').allTextContents()).map(x=>x.trim()))}`);await fillLabel(/Title|Job|Project/i,`${marker} Site Visit`);await optional(/Customer/i,`${marker} Customer`);await optional(/Date/i,'2026-09-10');await optional(/Time/i,'09:00');await optional(/Crew/i,'Crew A');await clickFormAction('Add Schedule Item');await expectText(`${marker} Site Visit`);await waitSaved();console.log('PASS schedule create/save');

 await nav('Employees');await clickButton(/Add Employee/i);console.log(`EMPLOYEE labels=${JSON.stringify((await page.locator('main label:visible').allTextContents()).map(x=>x.trim()))}`);await fillLabel(/^Name$/i,`${marker} Worker`);await optional(/Role/i,'Carpenter');await optional(/Phone/i,'9895550102');await optional(/Rate/i,'28');await clickFormAction('Add Employee');await expectText(`${marker} Worker`);await waitSaved();console.log('PASS employee create/save');

 await nav('Payroll');await clickButton(/New Pay Record/i);console.log(`PAYROLL labels=${JSON.stringify((await page.locator('main label:visible').allTextContents()).map(x=>x.trim()))}`);await optional(/Employee/i,`${marker} Worker`);await optional(/Hours/i,'40');await optional(/Rate/i,'28');await optional(/Date/i,'2026-09-09');await clickFormAction('New Pay Record');await expectText(`${marker} Worker`);await waitSaved();console.log('PASS payroll create/save');

 await nav('Documents');await clickButton(/Add Document Record/i);console.log(`DOCUMENT labels=${JSON.stringify((await page.locator('main label:visible').allTextContents()).map(x=>x.trim()))}`);await fillLabel(/Name|Document/i,`${marker} Scope Notes`);await optional(/Category|Type/i,'Project');await optional(/Project/i,`${marker} Remodel`);await optional(/Notes/i,'Launch readiness test document');await clickFormAction('Add Document Record');await expectText(`${marker} Scope Notes`);await waitSaved();console.log('PASS document create/save');

 await nav('Notes');const note=page.getByPlaceholder('Add a note...');await note.fill(`${marker} Owner note`);await note.press('Enter');await expectText(`${marker} Owner note`);await waitSaved();console.log('PASS note save');

 await nav('Settings');console.log(`SETTINGS labels=${JSON.stringify((await page.locator('main label:visible').allTextContents()).map(x=>x.trim()))}`);await optional(/Business|Company.*Name/i,`${marker} Construction`);await optional(/Phone/i,'9895550199');await clickButton(/Save Company Settings/i);await waitSaved();console.log('PASS settings save');

 const aiResult=await page.evaluate(async()=>{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'estimate',input:'Customer: E2E\nProject: Repair\nDescription: Replace 8 feet of damaged baseboard and paint to match.'})});return{status:r.status,body:await r.text()}});console.log(`AI status=${aiResult.status} body=${aiResult.body.slice(0,300)}`);if(aiResult.status!==200)throw new Error(`Live AI endpoint failed ${aiResult.status}: ${aiResult.body.slice(0,200)}`);console.log('PASS live AI endpoint');

 await page.reload({waitUntil:'networkidle'});await nav('Customers');await expectText(`${marker} Customer`);await nav('Projects');await expectText(`${marker} Remodel`);await nav('Employees');await expectText(`${marker} Worker`);await nav('Documents');await expectText(`${marker} Scope Notes`);console.log('PASS persistence after reload');await snap('production-deep-final');
}catch(e){failures.push(e?.stack||String(e));try{await snap('production-deep-failure')}catch{}}finally{await browser.close()}
for(const e of consoleErrors)console.log(`CONSOLE_ERROR ${e}`);for(const e of apiFailures)console.log(`HTTP_FAILURE ${e}`);if(consoleErrors.some(x=>!/favicon|hydration/i.test(x)))failures.push(...consoleErrors.map(x=>`console: ${x}`));if(apiFailures.length)failures.push(...apiFailures.map(x=>`http: ${x}`));if(failures.length){console.error('\nDEEP TEST FAILED');failures.forEach(x=>console.error(x));process.exit(1)}console.log('\nDEEP TEST PASSED');
