'use client'

import { useEffect,useMemo,useState } from 'react'
import { Bot,BriefcaseBusiness,CalendarDays,ClipboardList,DollarSign,FileSignature,FileText,FolderKanban,HardHat,Home,LogOut,Menu,NotebookPen,Plus,Receipt,Search,Settings,Sparkles,Users,WalletCards,X,Trash2,CheckCircle2,Pencil } from 'lucide-react'
import ContractWorkspace from './components/ContractWorkspace'
import JobTracker from './components/JobTracker'

type Project={id:number;customer:string;name:string;status:string;date:string;amount:number}
type Customer={id:number;name:string;phone:string;email:string;address:string}
type Invoice={id:number;customer:string;project:string;amount:number;status:string}
type Note={id:number;text:string}
type Estimate={id:number;customer:string;project:string;description:string;scope:string[];materials:string[];labor:string[];assumptions:string[];amount:number;status:string}
type Doc={id:number;type:string;customer:string;project:string;status:string;content?:string;approvedAt?:string;signature?:string;contractorSignature?:string;customerSignature?:string;contractDate?:string}
type ReceiptItem={id:number;merchant:string;amount:number;project:string;category:string;date:string;color?:string}
type ScheduleItem={id:number;title:string;customer:string;date:string;time:string;crew:string}
type Employee={id:number;name:string;role:string;phone:string;rate:number}
type PayrollItem={id:number;employee:string;hours:number;rate:number;gross:number;status:string;date:string;project?:string}
type FileRecord={id:number;name:string;category:string;project:string;notes:string}
type AppSettings={businessName:string;phone:string;email:string;address:string;estimateTerms:string}
type AppData={projects:Project[];customers:Customer[];invoices:Invoice[];notes:Note[];estimates:Estimate[];docs:Doc[];receipts:ReceiptItem[];schedule:ScheduleItem[];employees:Employee[];payroll:PayrollItem[];files:FileRecord[];settings:AppSettings}

const emptyData:AppData={projects:[],customers:[],invoices:[],notes:[],estimates:[],docs:[],receipts:[],schedule:[],employees:[],payroll:[],files:[],settings:{businessName:'',phone:'',email:'',address:'',estimateTerms:'Estimates are subject to field verification and final owner approval.'}}
const nav=[['Dashboard',Home],['Projects',FolderKanban],['Customers',Users],['AI Estimates',Sparkles],['Contracts',FileSignature],['Change Orders',ClipboardList],['Invoices',Receipt],['Receipts',WalletCards],['Schedule',CalendarDays],['Blueprints',FileText],['Employees',HardHat],['Payroll',DollarSign],['Documents',FileText],['Notes',NotebookPen],['Settings',Settings]] as const
function normalized(d:any):AppData{return{projects:Array.isArray(d?.projects)?d.projects:[],customers:Array.isArray(d?.customers)?d.customers:[],invoices:Array.isArray(d?.invoices)?d.invoices:[],notes:Array.isArray(d?.notes)?d.notes:[],estimates:Array.isArray(d?.estimates)?d.estimates:[],docs:Array.isArray(d?.docs)?d.docs:[],receipts:Array.isArray(d?.receipts)?d.receipts:[],schedule:Array.isArray(d?.schedule)?d.schedule:[],employees:Array.isArray(d?.employees)?d.employees:[],payroll:Array.isArray(d?.payroll)?d.payroll:[],files:Array.isArray(d?.files)?d.files:[],settings:{...emptyData.settings,...(d?.settings||{})}}}
async function ai(mode:string,input:string){const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,input})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error('Live AI could not generate this draft.');return String(body.text||'')}
const money=(n:number)=>'$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})

export default function Page(){const[section,setSection]=useState('Dashboard'),[data,setData]=useState<AppData>(emptyData),[loaded,setLoaded]=useState(false),[company,setCompany]=useState('BuildFlow Company'),[activeJob,setActiveJob]=useState<Project|null>(null);async function load(){const r=await fetch('/api/workspace',{cache:'no-store'});if(r.status===401){location.href='/login';return}const w=await r.json();setCompany(w.companyName||'BuildFlow Company');setData(normalized(w.data||{}));setLoaded(true)}useEffect(()=>{load()},[]);useEffect(()=>{if(!loaded)return;const t=setTimeout(()=>fetch('/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),450);return()=>clearTimeout(t)},[data,loaded]);if(!loaded)return <div className="loading"><HardHat/><b>Loading workspace…</b></div>;const unpaid=data.invoices.filter(i=>i.status!=='Paid').reduce((s,i)=>s+i.amount,0);return <div className="shell"><aside className="sidebar"><div className="brand"><div className="mark"><HardHat/></div><div><b>BuildFlow</b><span>HQ</span></div></div><div className="company"><small>COMPANY</small><strong>{data.settings.businessName||company}</strong></div><nav>{nav.map(([n,I])=><button key={n} className={section===n?'active':''} onClick={()=>{setSection(n);setActiveJob(null)}}><I size={18}/>{n}</button>)}</nav></aside><main><header><div><h1>{section}</h1><p>{data.settings.businessName||company} · BuildFlow HQ</p></div></header>{activeJob?<JobTracker project={data.projects.find(p=>p.id===activeJob.id)||activeJob} data={data} setData={setData} onClose={()=>setActiveJob(null)}/>:section==='Contracts'?<ContractWorkspace data={data} setData={setData} ai={ai}/>:section==='Dashboard'?<Dashboard data={data} unpaid={unpaid} setSection={setSection}/>:section==='Projects'?<Projects data={data} setData={setData} startJob={setActiveJob}/>:section==='AI Estimates'?<Estimates data={data} setData={setData}/>:<Module section={section} data={data} setData={setData}/>}<footer>BuildFlow HQ · Multi-tenant workspace</footer></main></div>}

function Dashboard({data,unpaid,setSection}:{data:AppData,unpaid:number,setSection:(s:string)=>void}){return <><section className="hero"><div><span>CONTRACTOR HQ</span><h2>Run the whole business from one place.</h2><p>Jobs, estimates, contracts, signatures, costs, labor and customer records.</p></div><button onClick={()=>setSection('AI Estimates')}><Sparkles/> Build AI Estimate</button></section><section className="stats"><button className="statButton" onClick={()=>setSection('Projects')}><Stat label="Active Jobs" value={String(data.projects.filter(p=>p.status==='In Progress').length)} sub="currently active"/></button><button className="statButton" onClick={()=>setSection('Invoices')}><Stat label="Unpaid Invoices" value={money(unpaid)} sub="open balance"/></button><button className="statButton" onClick={()=>setSection('Contracts')}><Stat label="Signed Contracts" value={String(data.docs.filter(d=>d.type==='Contracts'&&d.status==='Executed Contract').length)} sub="executed agreements"/></button></section></>}
function Projects({data,setData,startJob}:{data:AppData,setData:(d:AppData)=>void,startJob:(p:Project)=>void}){const[customer,setCustomer]=useState(''),[name,setName]=useState(''),[amount,setAmount]=useState('');function add(){if(!customer.trim()||!name.trim())return;setData({...data,projects:[{id:Date.now(),customer:customer.trim(),name:name.trim(),status:'Estimate',date:'Not scheduled',amount:Number(amount||0)},...data.projects]});setCustomer('');setName('');setAmount('')}return <div className="workspace"><Head title="Projects" text="Start a job to track expenses, labor and customer reports."/><div className="builderGrid inlineAction"><Field label="Customer" value={customer} set={setCustomer}/><Field label="Project" value={name} set={setName}/><Field label="Estimate amount" value={amount} set={setAmount} type="number"/><button className="primary" onClick={add}><Plus/>New Project</button></div>{data.projects.map(p=><div className="wideRow" key={p.id}><div className="grow"><b>{p.name}</b><span>{p.customer}</span></div><strong>{money(p.amount)}</strong><span className="badge">{p.status}</span><button className="primary" onClick={()=>startJob(p)}>{p.status==='In Progress'?'Open Job':'Start Job'}</button></div>)}</div>}
function Estimates({data,setData}:{data:AppData,setData:(d:AppData)=>void}){const[c,setC]=useState(''),[p,setP]=useState(''),[desc,setDesc]=useState(''),[working,setWorking]=useState(false);async function gen(){if(!c||!p||!desc)return;setWorking(true);try{const text=await ai('estimate',`Customer: ${c}\nProject: ${p}\nDescription: ${desc}`);let j:any={};try{j=JSON.parse(text.replace(/^```json\s*/i,'').replace(/```$/,'').trim())}catch{j={scope:[text],amount:0}};setData({...data,estimates:[{id:Date.now(),customer:c,project:p,description:desc,scope:j.scope||[],materials:j.materials||[],labor:j.labor||[],assumptions:j.assumptions||[],amount:Number(j.amount||0),status:'AI Draft'},...data.estimates]})}finally{setWorking(false)}}return <div className="workspace"><Head title="AI Estimates" text="Generate contractor estimate drafts."/><div className="builderGrid"><Field label="Customer" value={c} set={setC}/><Field label="Project" value={p} set={setP}/><label className="full">Job description<textarea value={desc} onChange={e=>setDesc(e.target.value)}/></label><button className="primary full" onClick={gen} disabled={working}>{working?'Generating…':'Generate Estimate'}</button></div>{data.estimates.map(e=><Row key={e.id} title={e.project} sub={e.customer} amount={e.amount} status={e.status}/>)}</div>}
function Module({section,data,setData}:{section:string,data:AppData,setData:(d:AppData)=>void}){if(section==='Invoices')return <div className="workspace"><Head title="Invoices" text="Customer invoices."/>{data.invoices.map(i=><Row key={i.id} title={i.customer} sub={i.project} amount={i.amount} status={i.status}/>)}</div>;if(section==='Receipts')return <div className="workspace"><Head title="Receipts" text="Job expenses are also recorded from Start Job."/>{data.receipts.map(r=><Row key={r.id} title={r.merchant} sub={`${r.project} · ${r.category}`} amount={r.amount}/>)}</div>;if(section==='Payroll')return <div className="workspace"><Head title="Payroll" text="Labor hours recorded from active jobs."/>{data.payroll.map(p=><Row key={p.id} title={p.employee} sub={`${p.hours} hrs · ${p.project||''}`} amount={p.gross}/>)}</div>;return <div className="workspace"><Head title={section} text="Organized inside this company workspace."/></div>}
function Head({title,text}:{title:string,text:string}){return <div className="workspaceHead"><div><h2>{title}</h2><p>{text}</p></div></div>};function Stat({label,value,sub}:{label:string,value:string,sub:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>};function Row({title,sub,amount,status}:{title:string,sub:string,amount?:number,status?:string}){return <div className="wideRow"><div className="jobicon"><BriefcaseBusiness/></div><div className="grow"><b>{title}</b><span>{sub}</span></div>{amount!==undefined&&<strong>{money(amount)}</strong>}{status&&<span className="badge">{status}</span>}</div>};function Field({label,value,set,type='text'}:{label:string,value:string,set:(v:string)=>void,type?:string}){return <label>{label}<input type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
